### ISSUE TITLE
Values of soil temperature when groundwater coupling

### ISSUE THREAD

**Issue by SarahAlidoost** [EcoExtreML/STEMMUS_SCOPE#242]
I'm afraid this did not fully fix the issue... While there is no negative spike anymore, a growing positive spike does form over time:

![image](https://github.com/user-attachments/assets/17afa6ae-54bf-445f-ab57-1160337c26bd)

_Originally posted by @BSchilperoort in https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/239#issuecomment-2242138630_

**Comment by SarahAlidoost** [comment]
:red_circle: This issue should be fixed before releasing stemmus_scope, see details in https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/239

**Comment by BSchilperoort** [comment]
> if it is changed to default values in [stemmus_scope i.e. 1950.0](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Bgroundwater/initializeGroundwaterSettings.m#L27), the issue is gone

The issue is still there, it occurs at the groundwater depth. See:
![image](https://github.com/user-attachments/assets/8583ff88-1322-4e9a-8e37-fd3ef5a36379)

**Comment by SarahAlidoost** [comment]
These are the values of the test that creates the plots:

Location=ZA-Kru
StartTime=2001-01-01T00:00
EndTime=2001-01-01T10:30

```
model.set_value("groundwater_coupling_enabled", np.array([True]))
model.set_value("groundwater_elevation_top_aquifer", np.array([2000.]))
model.set_value("groundwater_head_bottom_layer", np.array([1950.]))  # 50 cm under ground surface
model.set_value("groundwater_temperature", np.array([23.])) # optional. 
```

**Comment by MostafaGomaa93** [comment]
@SarahAlidoost @yijianzeng 

After our meeting today, I test again by setting the `tempBotm` in this [line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/calculateBoundaryConditions.m#L19C7-L19C75) to `tempBotm = SoilVariables.TT(indxBotm)` which is = 22.96 for the ZA-Kru and the problem is still there.

**Comment by yijianzeng** [comment]
> ```
>           I'm afraid this did not fully fix the issue... While there is no negative spike anymore, a growing positive spike does form over time:
> ```

This depends on the temperature value you set for groundwater temperature. See my other comments [here]([https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/239#issuecomment-2242948053]).

**Comment by MostafaGomaa93** [comment]
> > ```
> >           I'm afraid this did not fully fix the issue... While there is no negative spike anymore, a growing positive spike does form over time:
> > ```
> 
> This depends on the temperature value you set for groundwater temperature. See my other comments [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/239#issuecomment-2242948053).

Yes, I mean your suggestion by **fixing the groundwater temperature = soil temperature wherever GW reaches a certain depth of the soil column.** didn't solve the problem yet. So, it looks like there is a bug indeed

**Comment by MostafaGomaa93** [comment]
Please have a look at these two sheets at the column with first value = 230 (depth = 230), the depth above the groundwater table (groundwater depth = 250). In both cases, you will find the values at that column are lower than the two columns before and after that column (columns 220 and 245) which case these strange peaks in @BSchilperoort figures

case 1: setting bottom boundary = groundwater temperature = 23
[Sim_Temp_gwtemp=soiltemp.csv](https://github.com/user-attachments/files/16347615/Sim_Temp_gwtemp.soiltemp.csv)

case 2: setting bottom temperature boundary = soil temperature, which is = 22.96
[Sim_Temp_no_coupling.csv](https://github.com/user-attachments/files/16347616/Sim_Temp_no_coupling.csv)

**Comment by yijianzeng** [comment]
> ![soil_temp_plot](https://private-user-images.githubusercontent.com/55081872/351017527-d2815615-059b-45de-a8c5-d4a800c5af16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjY1MjksIm5iZiI6MTcyMTcyNjIyOSwicGF0aCI6Ii81NTA4MTg3Mi8zNTEwMTc1MjctZDI4MTU2MTUtMDU5Yi00NWRlLWE4YzUtZDRhODAwYzVhZjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA5MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMjEyM2Y5YmNkNWEzM2VlZDI1MGZlNjcwMDBkY2YzMmRkODNkZWE5OGUzMWVmOTZiZmMwZWY1NDc3YjgzNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cbZYNouB80LEbPq5CuPrdvtH57t15pxwiY4-tCvSVNw)
> 
> @MostafaGomaa93 is there any condition for the values of `groundwater_head_bottom_layer`?

From this plot, it seems to me at 50cm the groundwater temperature of 23 degree is used to replace soil temperature profile below 50cm?

**Comment by yijianzeng** [comment]
> I also noticed the implementation of `SoilVariable.TT` and `TT` is not ideal in `STEMMUS_SCOEP.m`. However, this is a separate issue. It would be better if TT is replaced by SoilVariable.TT everywhere in the script, the same for [these variables](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/STEMMUS_SCOPE.m#L246-L252).

'TT' is the soil temperature updated after the current time step running.

**Comment by yijianzeng** [comment]
> The issue is still there, it occurs at the groundwater depth. See:

I would say this is not the issue, but the artifact induced by manually setting the groundwater temperature.

**Comment by MostafaGomaa93** [comment]
> I would say this is not the issue, but the artifact induced by manually setting the groundwater temperature.

The issue also occurs if we set `groundwater temperature = soil temperature of bottom layer` and the issue is there at any location of the groundwater table. see another example with a groundwater table is 3.5 m below the surface

![st](https://github.com/user-attachments/assets/08a82a37-1b53-43fd-a4f4-f563b8b2d3d1)

**Comment by yijianzeng** [comment]
> @SarahAlidoost @yijianzeng
> 
> After our meeting today, I test again by replacing the `tempBotm` in this [line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/calculateBoundaryConditions.m#L19C7-L19C75) by `tempBotm = SoilVariables.TT(indxBotm)` which is = 22.96 for the ZA-Kru and the problem is still there.

Hi Mostafa, please try the following:
- first, check the soil temperature profile without coupling the groundwater flow.
- second, check the soil temperature profile after coupling the groundwater flow.
- third, try to see if you are sure that at the depth of the groundwater table, you did not change the soil temperature at that depth

**Comment by MostafaGomaa93** [comment]
I think the problem is relaxed with the time. Have a look to this figure with
Location=ZA-Kru
StartTime=2001-01-01T00:00
EndTime=2001-01-08T00:00
gwtemp

This solution is without the modification in this [line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/solveTridiagonalMatrixEquations.m#L32) (once agreed, we can delete it)

 
![st_gwtemp=soiltemp](https://github.com/user-attachments/assets/01131b47-d7bf-4de8-9999-ae3ab3dae42f)

**Comment by MostafaGomaa93** [comment]
another test with changing the groundwater depth over time

![sm st_change_gwl](https://github.com/user-attachments/assets/bbc994ea-7f42-4ad0-b7e0-c2715da90d15)

**Comment by SarahAlidoost** [comment]
The current coupling implementation has several issues related to coding and setting physical parameters. Here is a summary:

**Coding issues:**
1- introducing `indxBotm` to the modules `+energy`, `+soilmoisture` and `+dryair` is not needed at most parts and causes bugs for example [in this line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Bsoilmoisture/calculateTimeDerivatives.m#L64) index of `P_gg` is still 2. Other examples of such bugs are in [SV.T(2)](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/assembleCoefficientMatrices.m#L35), [C2(1, 2)](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/assembleCoefficientMatrices.m#L82). 

2- setting the values of RHS in modules `+energy` [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/solveTridiagonalMatrixEquations.m#L28-L30), `+soilmoisture`  [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Bsoilmoisture/solveTridiagonalMatrixEquations.m#L27-L30) are not correct. Model should calculate those values. 

3- The soil temperature `SoilVariables.TT` should be set in `update` loop [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/STEMMUS_SCOPE.m#L334). But, due to current codes, the variable `TT` should be set too.

4- (minor issue) RHS should be defined in module `+energy` as `RHS = InitialValues.RHS;` in `assembleCoefficientMatrices.m`

**Setting physical parameters:**

1-  The coupling only sets soil temperature `SoilVariables.TT`. But, it seems that `SoilVariables.T` and `T` are also related and should be set accordingly. 

2- in coupling [BoundaryCondition.NBChB = 1;](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/STEMMUS_SCOPE.m#L337), which is only valid for the sites with landcover 'Croplands'. But, for example `ZA-Kru` is not a 'Croplands'. 

3- Values of `RHS(1)`  in `+soilmoisture`  is calculated as `headBotmLayer - topLevel + soilThick(indxBotmLayer_R)`. First of all the units don't match. Second, this equation might return zero. 

4- The [condition](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/solveEnergyBalanceEquations.m#L34)  in `energy/solveEnergyBalanceEquations.m` should be checked because it is using `ForcingData.Tmin`. This might not be valid in the case of coupling.

**Comment by SarahAlidoost** [comment]
@MostafaGomaa93 here are the codes that we discussed at our meeting. 

<details> 
<summary>Codes for plotting the soil temperature values:</summary>

```python
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import xarray as xr

# Read the CSV file
csv_path = "/path_to/output/ZA-Kru_2023-09-06-1228/Sim_Temp.csv"

# Read the CSV file
df = pd.read_csv(csv_path, header=None)

# Get the first row as depths
depths = df.iloc[0].values.astype(float) * -1

# Get the rest of the data as soil_temperature
soil_temperature = df.iloc[3:].values.astype(float)

# Create a time index
time = np.arange(1, len(df)-2)

# Create the xarray DataArray
da_t = xr.DataArray(
    data=soil_temperature,
    dims=("time", "depth"),
    coords={"time": time, "depth": depths},
)

da_t.isel(time=0).plot(y="depth")
da_t.isel(time=1).plot(y="depth")
da_t.isel(time=2).plot(y="depth")
```
</details>

<details> 
<summary>Codes for setting values through BMI:</summary>

The notebook is available in pull request https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/pull/101. 

```python
# as an example, every time step i, the value of groundwater_head_bottom_layer is set to [1950.-i*4])
model.set_value("groundwater_head_bottom_layer", np.array([1950.-i*4]))
```
</details>

<details> 
<summary>Git commands for working with BMI implementation:</summary>

Based on the [pystemmusscope documentation.](https://pystemmusscope.readthedocs.io/en/latest/CONTRIBUTING/) 

```bash
git clone https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing.git
cd STEMMUS_SCOPE_Processing
git checkout bmi-groundwater-coupling  # switch to BMI branch
git checkout - b name_of_your_branch  # create your own branch
pip install -e .[dev]  # install pystemmusscope in development mode
pip install jupyterlab
jupyter lab  # start jupyter lab
```
</details>

**Comment by MostafaGomaa93** [comment]
Thanks a lot for the comments. here are my replies

> The current coupling implementation has several issues related to coding and setting physical parameters. Here is a summary:
> 
> **Coding issues:** 1-(major) introducing `indxBotm` to the modules `+energy`, `+soilmoisture` and `+dryair` is not needed at most parts and causes bugs for example [in this line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Bsoilmoisture/calculateTimeDerivatives.m#L64) index of `P_gg` is still 2. Other examples of such bugs are in [SV.T(2)](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/assembleCoefficientMatrices.m#L35), [C2(1, 2)](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/assembleCoefficientMatrices.m#L82).
> 
Yes, those 3 are my mistakes, I have corrected them in the [new pull request](https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/245). However, the changes doesn't change the results because the three changes are in the condition when ModelSettings.Soilairefc = 1, and by default its = 0 (see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/01007009110c715cab3d87da7819dc3153481a9a/src/%2Bsoilmoisture/calculateTimeDerivatives.m#L61-L64), [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/01007009110c715cab3d87da7819dc3153481a9a/src/%2Benergy/assembleCoefficientMatrices.m#L35-L36) and [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/01007009110c715cab3d87da7819dc3153481a9a/src/%2Benergy/assembleCoefficientMatrices.m#L82-L83)).

> 2- setting the values of RHS in modules `+energy` [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/solveTridiagonalMatrixEquations.m#L28-L30), `+soilmoisture` [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Bsoilmoisture/solveTridiagonalMatrixEquations.m#L27-L30) are not correct. Model should calculate those values.
> 
The model indeed should calculate the RHS for all layers. However, when we set the location of the groundwater table as the bottom boundary of the soil, then all layers below the groundwater table are saturated layers (full with water), so there is no soil anymore and STEMMUS is not adapted to calculate the variables below the groundwater table, and thats why we will couple STEMMUS_SCOPE to MODFLOW. So, the RHS of the saturated layers in the `soilmoisture`, `energy`, and `dryair` modules must be set manually to certain values (as we did already).

> 3- (major)The soil temperature `SoilVariables.TT` should be set in `update` loop [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/STEMMUS_SCOPE.m#L334). But, due to current codes, the variable `TT` should be set too.
> 
Okay, I add them [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/9d9588fdc0ce26b4bf3b8aea8933d0fccbd2fb3f/src/STEMMUS_SCOPE.m#L349-L351)

> 4- (minor issue) RHS should be defined in module `+energy` as `RHS = InitialValues.RHS;` in `assembleCoefficientMatrices.m`
> 
Okay, I have add this in this [line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/01007009110c715cab3d87da7819dc3153481a9a/src/%2Benergy/assembleCoefficientMatrices.m#L33). However, it doesn't change the results

> **Setting physical parameters:**
> 
> 1- (major)The coupling only sets soil temperature `SoilVariables.TT`. But, it seems that `SoilVariables.T` and `T` are also related and should be set accordingly.
> 
 I add the `SoilVariables.T` and `T` [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/9d9588fdc0ce26b4bf3b8aea8933d0fccbd2fb3f/src/STEMMUS_SCOPE.m#L349-L351). Is that what you mean or we need further edits?

> 2- in coupling [BoundaryCondition.NBChB = 1;](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/STEMMUS_SCOPE.m#L337), which is only valid for the sites with landcover 'Croplands'. But, for example `ZA-Kru` is not a 'Croplands'.
> 
The `BoundaryCondition.NBChB = 1` means that the bottom boundary is a head boundary and it is not related to the landcover type. In principle, if we know the head at the bottom of the soil (which is the case when we use MODFLOW), then we use `BoundaryCondition.NBChB = 1`. I think Yijian may help to answer why for the case of  'Croplands',  `BoundaryCondition.NBChB = 1` 

> 3- Values of `RHS(1)` in `+soilmoisture` is calculated as `headBotmLayer - topLevel + soilThick(indxBotmLayer_R)`. First of all the units don't match. Second, this equation might return zero.
> 
If the `BoundaryCondition.NBChB = 1`, then the RHS is a head and has units of cm. If the `BoundaryCondition.NBChB = 2`, then the RHS is a flux and has units of cm/sec. In the case of groundwater coupling, RHS has units of cm and the `headBotmLayer`, `topLevel`, `soilThick(indxBotmLayer_R)` are all in cm. and the value of RHS(indexbotm) is indeed close to zero  

> 4- (major)The [condition](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/solveEnergyBalanceEquations.m#L34) in `energy/solveEnergyBalanceEquations.m` should be checked because it is using `ForcingData.Tmin`. This might not be valid in the case of coupling.
>
I removed this condition while testing but found that no difference in the results. Maybe Yijian could clarify what is the purpose of this condition

**Comment by MostafaGomaa93** [comment]
> @MostafaGomaa93 here are the codes that we discussed at our meeting.
> 
> Codes for plotting the soil temperature values:

Thanks so much for the codes. I have used the plotting code to observe the spikes in the figures below. However, the lines in the figures are sharp and not that smooth as in @BSchilperoort figures

**Comment by MostafaGomaa93** [comment]
Top Right: `groundwater depth = 50`, `groundwater temperature = NaN`, ([average condition](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/solveTridiagonalMatrixEquations.m#L32)) is not used
no spikes
Top left:  `groundwater depth = 150`, `groundwater temperature = NaN`,  average condition is not used
at time = 300 -> spikes are minor (one negative spike and one positive spike), marked by black circle 
Bottom Right: `groundwater depth = 150`, `groundwater temperature = NaN`,  average condition is used
at time = 300 -> spikes are minor (only one positive spike), marked by black circle 
Bottom left: `groundwater depth = 250`, `groundwater temperature = NaN`,  average condition is not used
at time = 300 -> one minor positive spike, marked by black circle 

![check_spikes_4](https://github.com/user-attachments/assets/c5fab8c2-14cc-4d19-8c15-04d4a3e406ea)

**Comment by MostafaGomaa93** [comment]
Another two examples at `groundwater depth = 250` and ([average condition](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/solveTridiagonalMatrixEquations.m#L32)) is not used
left: `groundwater temperature = 23`
at time = 300 -> one positive spike

right: `groundwater temperature = 17`, 
at time = 300 -> no spikes

![check_spikes_2](https://github.com/user-attachments/assets/b80fd7ce-750f-4bd5-a835-0d97d9cabd09)

**Comment by SarahAlidoost** [comment]
> > @MostafaGomaa93 here are the codes that we discussed at our meeting.
> > Codes for plotting the soil temperature values:
> 
> Thanks so much for the codes. I have used the plotting code to observe the spikes in the figures below. However, the lines in my figures are sharp and not that smooth as in @BSchilperoort figures (don't know why)
> 

The code that I provided plots the entire depth profile (0, 5 m). In your plots here, the y axis is between (-20, 2.5 cm). Please make sure that you can create the exact same plots. So we are looking at the same things.

**Comment by SarahAlidoost** [comment]
@MostafaGomaa93 the plots below are created using your changed code in #245, for two sites: ZA-Kru "Savannas" and DE-Geb "cropland". The plots show soil temperature and soil moisture in case no coupling and coupling with different temperatures and depths. The issues are indicated in each plot. it seems that results are better for DE-Geb "cropland" than ZA-Kru "Savannas". But the results are the same for DE-Geb with different temperatures 23 and 17, e.g. see Fig 3. It would be good to check the code for one more site with "cropland".

The issue of the first time step can be fixed by setting TT in the update section, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/245/files#r1700049191).

As mentioned before, in stemmusscope (without coupling), `BoundaryCondition.NBChB` is set to 1 for sites with "cropland" whereas 3 for other sites. However, in groundwater coupling, `BoundaryCondition.NBChB` is set to 1 for all sites. @yijianzeng Is this a valid assumption? see definition [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Binit/setBoundaryCondition.m#L63-L71).

Fig 1: ZA-Kru "Savannas"
![Slide9](https://github.com/user-attachments/assets/0886be2c-b14d-4283-8920-cc87d1000c3e)

Fig 2: DE-Geb "cropland"
![Slide10](https://github.com/user-attachments/assets/aee7e28f-8b9f-4543-92ea-a3c0f3e91493)
Fig 3: DE-Geb "cropland"
![Slide11](https://github.com/user-attachments/assets/b7888aae-e771-4976-bb2a-8aea2dd8dbcf)

**Comment by SarahAlidoost** [comment]
@MostafaGomaa93 Another physical condition that should be set correctly is `elseif groundWaterDepth > Tot_Depth` in [calculateGroundWaterDepth](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Bgroundwater/calculateGroundWaterDepth.m#L9). If `headBotmLayer=1495.0`, this `elseif groundWaterDepth > Tot_Depth` will be True and `indxBotmLayer` will be undefined in [calculateIndexBottomLayer](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Bgroundwater/calculateIndexBottomLayer.m#L30). This causes the model run to fail. There should be a condition to check whether the values of `headBotmLayer` are in a valid range.

**Comment by SarahAlidoost** [comment]
@MostafaGomaa93  This is the output csv file for 

- Location=DE-Geb,
- StartTime=2001-01-01T00:00,
- EndTime=2001-01-10T01:00,
- groundwater_elevation_top_aquifer=2000,
- groundwater_head_bottom_layer=1950,
- groundwater_temperature=Nan.

[Sim_Temp.csv](https://github.com/user-attachments/files/16493945/Sim_Temp.csv)

**Comment by MostafaGomaa93** [comment]
> > > @MostafaGomaa93 here are the codes that we discussed at our meeting.
> > > Codes for plotting the soil temperature values:
> > 
> > 
> > Thanks so much for the codes. I have used the plotting code to observe the spikes in the figures below. However, the lines in my figures are sharp and not that smooth as in @BSchilperoort figures (don't know why)
> 
> The code that I provided plots the entire depth profile (0, 5 m). In your plots here, the y axis is between (-20, 2.5 cm). Please make sure that you can create the exact same plots. So we are looking at the same things. You can also generate an exe file and run the BMI notebook to make sure that plots are the same.

Thanks for the observation. I have updated my figures. I think the provided code may need this slight change

`depths = df.iloc[0].index.astype(float) * -1` 
instead of
`depths = df.iloc[0].values.astype(float) * -1`

**Comment by MostafaGomaa93** [comment]
> > > > @MostafaGomaa93 here are the codes that we discussed at our meeting.
> > > > Codes for plotting the soil temperature values:
> > > 
> > > 
> > > Thanks so much for the codes. I have used the plotting code to observe the spikes in the figures below. However, the lines in my figures are sharp and not that smooth as in @BSchilperoort figures (don't know why)
> > 
> > 
> > The code that I provided plots the entire depth profile (0, 5 m). In your plots here, the y axis is between (-20, 2.5 cm). Please make sure that you can create the exact same plots. So we are looking at the same things. You can also generate an exe file and run the BMI notebook to make sure that plots are the same.
> 
> Thanks for the observation. I have updated my figures. I think the provided code may need this slight change
> 
> `depths = df.iloc[0].index.astype(float) * -1` instead of `depths = df.iloc[0].values.astype(float) * -1`

After i have updated my figures, i think there are spikes in the first couple of time steps (time step = 1, and tim step = 20). At longer timestep (timestep = 60, timestep = 300), spikes are very minor or not there at all. So, the spikes problem relaxed with the time. 

I also think that it is the same case with the figures that @SarahAlidoost posted

**Comment by MostafaGomaa93** [comment]
> @MostafaGomaa93 Another physical condition that should be set correctly is `elseif groundWaterDepth > Tot_Depth` in [calculateGroundWaterDepth](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Bgroundwater/calculateGroundWaterDepth.m#L9). If `headBotmLayer=1495.0`, this `elseif groundWaterDepth > Tot_Depth` will be True and `indxBotmLayer` will be undefined in [calculateIndexBottomLayer](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Bgroundwater/calculateIndexBottomLayer.m#L30). This causes the model run to fail. There should be a condition to check whether the values of `headBotmLayer` are in a valid range.

Indeed, if `headBotmLayer` goes below `Tot_Depth`, then model will fail. The user should have a basic knowledge about the range of the groundwater depth of the site. If the groundwater depth is close to or larger than 5 m, then the `Tot_Depth` shoud be increased and be larger than 5 m. A solution is provided in [this](https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/243) PR (hopefully we can check later after the soil temp issue)

**Comment by MostafaGomaa93** [comment]
>  The code that I provided plots the entire depth profile (0, 5 m). In your plots here, the y axis is between (-20, 2.5 cm). Please make sure that you can create the exact same plots. So we are looking at the same things. You can also generate an exe file and run the BMI notebook to make sure that plots are the same.
> 

 Thanks for the observation. I have updated my figures. I think the provided code may need this slight change
 `depths = df.iloc[0].index.astype(float) * -1` instead of `depths = df.iloc[0].values.astype(float) * -1`
 
After i have updated my figures, i think there are spikes in the first couple of time steps (time step = 1, and time step = 20, spikes are marked with grey circle). At longer timestep (timestep = 60, timestep = 300, spikes are marked with black circle), spikes are very minor or not there at all. So, the spikes problem relaxed with the time.

I also think that it is the same case with the figures that @SarahAlidoost posted

**Comment by yijianzeng** [comment]
> > > ```
> > >           I'm afraid this did not fully fix the issue... While there is no negative spike anymore, a growing positive spike does form over time:
> > > ```
> > 
> > 
> > This depends on the temperature value you set for groundwater temperature. See my other comments [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/239#issuecomment-2242948053).
> 
> Yes, I mean your suggestion by **fixing the groundwater temperature = soil temperature wherever GW reaches a certain depth of the soil column.** didn't solve the problem yet. So, it looks like there is a bug indeed

Mostafa, as i mentioned the soil moisture content will impact soil temperature simulations. This is about soil physics.

**Comment by yijianzeng** [comment]
> > **Setting physical parameters:**
> > 1- (major)The coupling only sets soil temperature `SoilVariables.TT`. But, it seems that `SoilVariables.T` and `T` are also related and should be set accordingly.
> 
> I add the `SoilVariables.T` and `T` [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/9d9588fdc0ce26b4bf3b8aea8933d0fccbd2fb3f/src/STEMMUS_SCOPE.m#L349-L351). Is that what we need only or we need further edits?

'SoilVariables.T' means the soil temperature calculated from the last time step. 'TT' means soil temperature calculated at this time step.

**Comment by yijianzeng** [comment]
> > 2- in coupling [BoundaryCondition.NBChB = 1;](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/STEMMUS_SCOPE.m#L337), which is only valid for the sites with landcover 'Croplands'. But, for example `ZA-Kru` is not a 'Croplands'.
> 
> The `BoundaryCondition.NBChB = 1` means that the bottom boundary is a head boundary and it is not related to the landcover type. In principle, if we know the head at the bottom of the soil (which is the case when we use MODFLOW), then we use `BoundaryCondition.NBChB = 1`. I think Yijian may help to answer why for the case of 'Croplands', `BoundaryCondition.NBChB = 1`

I agree with Mostafa, that the bottom boundary condition is not related to landcover type.

**Comment by yijianzeng** [comment]
> > 4- (major)The [condition](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Benergy/solveEnergyBalanceEquations.m#L34) in `energy/solveEnergyBalanceEquations.m` should be checked because it is using `ForcingData.Tmin`. This might not be valid in the case of coupling.
> 
> I removed this condition while testing but found that no difference in the results. Maybe Yijian could clarify what is the purpose of this condition

I think Lianyu added this to allow the numerical model to converge better.

**Comment by yijianzeng** [comment]
> As mentioned before, in stemmusscope (without coupling), `BoundaryCondition.NBChB` is set to 1 for sites with "cropland" whereas 3 for other sites. However, in groundwater coupling, `BoundaryCondition.NBChB` is set to 1 for all sites. @yijianzeng Is this a valid assumption? see definition [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Binit/setBoundaryCondition.m#L63-L71).

Most of time, we say the bottom boundary condition is free drainage. When it is coupled with groundwater model, we know the soil profile emerged in groundwater will be saturated, then we know the matric head will be '0'. 

In short, test, it is a valid assumption.

**Comment by SarahAlidoost** [comment]
@BSchilperoort here are the results of the model for other sites, showing that there is an issue when the temperature is Nan. This has been discussed with @MostafaGomaa93 and will be fixed in #245. The coupling results look okay for other sites except for some spikes in `Fig 0-DE-Seh (croplands), no coupling` which is not related to ground water coupling.  

DE-Seh (croplands):
![Slide5](https://github.com/user-attachments/assets/8a69be1d-b87c-466f-baa7-6c45aae5ff78)

ES-LMa (Savannas):
![Slide7](https://github.com/user-attachments/assets/a5243827-41a7-45e2-8a45-d5bb600a1b74)

AU-Stp (grassland):
![Slide9](https://github.com/user-attachments/assets/c9a5697a-39b7-4b5b-ae7e-13882920c11d)
